# Generated by Django 3.1.7 on 2021-05-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'product_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.CharField(db_column='variant_id', max_length=255)),
                ('variant_name', models.CharField(blank=True, db_column='variant_name', max_length=255, null=True)),
                ('price', models.FloatField(db_column='price')),
                ('quantity', models.IntegerField(db_column='quantity')),
            ],
            options={
                'db_table': 'product_variant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VariantValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, db_column='value', max_length=255, null=True)),
            ],
            options={
                'db_table': 'variant_value',
                'managed': False,
            },
        ),
    ]
