# Generated by Django 3.1.7 on 2021-06-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_productattribute_productvariant_variantvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFormm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('dvvc', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
