# Generated by Django 3.1.7 on 2021-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_orderformm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserOrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maDonHang', models.CharField(blank=True, max_length=255, null=True)),
                ('ngayDat', models.CharField(blank=True, max_length=255, null=True)),
                ('khachHang', models.CharField(blank=True, max_length=255, null=True)),
                ('thanhToan', models.CharField(blank=True, max_length=255, null=True)),
                ('tinhTrang', models.CharField(blank=True, max_length=255, null=True)),
                ('tongTien', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
